twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        vich_uploader_asset: '@Vich\UploaderBundle\Twig\Extension\UploaderExtension'

when@test:
    twig:
        strict_variables: true
